version: '3.4'

services:
  motoapp:
    image: motorrentalapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: MotoRentalDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
